// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCysp1N_Q3eGe68YFTUytqj7XPZa0K7DWY',
    appId: '1:626924381050:android:90f35a5395b77622b5ecc3',
    messagingSenderId: '626924381050',
    projectId: 'friendlink-f1e64',
    databaseURL: 'https://friendlink-f1e64-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'friendlink-f1e64.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWvWov2Oxloz9yMqjNEM846GTrIq4d8BI',
    appId: '1:626924381050:ios:7a13e922acf263a0b5ecc3',
    messagingSenderId: '626924381050',
    projectId: 'friendlink-f1e64',
    databaseURL: 'https://friendlink-f1e64-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'friendlink-f1e64.firebasestorage.app',
    iosBundleId: 'com.example.friendlink',
  );
}
